# Generated by Django 5.0.4 on 2024-04-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='starrating',
            options={'ordering': ['-star']},
        ),
        migrations.AddField(
            model_name='movie',
            name='link_movie',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка на фильм'),
            preserve_default=False,
        ),
    ]
