# Generated by Django 5.0.4 on 2024-04-16 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_by',
            field=models.DateField(auto_now_add=True, default='2000-12-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='to_movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_movie', to='movies.movie', verbose_name='Фильм'),
        ),
    ]
