# Generated by Django 5.0.4 on 2024-04-17 13:56

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_comment_created_by_alter_comment_to_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to=movies.models.poster_movie_path),
        ),
    ]
